# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Prefabulated
tagline:          ''
description:      'Ill-advised projects and harebrained schemes'
url:              http://prefabulated.com

author:
  name:           'Dan Stoza'
  url:            http://prefabulated.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dstoza/dstoza.github.io
